services:
  - name: pikatube-backend
    type: web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node database.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 1000
    autoDeploy: true
